Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 136, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 104, in render
    self._set_content(self.rendered_content)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 81, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 48, in top-level template code
    {% if perms.scrum.add_team %}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 376, in getattr
    return obj[attribute]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/context_processors.py", line 12, in __getitem__
    return self.user.has_perm("%s.%s" % (self.module_name, perm_name))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 248, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 16, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 8, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 98, in get_user
    user_id = request.session[SESSION_KEY]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 39, in __getitem__
    return self._session[key]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 165, in _get_session
    self._session_cache = self.load()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/cached_db.py", line 32, in load
    data = super(SessionStore, self).load()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 19, in load
    expire_date__gt=timezone.now()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 131, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/query.py", line 361, in get
    num = len(clone)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/query.py", line 85, in __len__
    self._result_cache = list(self.iterator())
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/query.py", line 291, in iterator
    for row in compiler.results_iter():
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 763, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 817, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/backends/__init__.py", line 319, in cursor
    cursor = util.CursorWrapper(self._cursor(), self)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 288, in _cursor
    self._sqlite_create_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 278, in _sqlite_create_connection
    self.connection = Database.connect(**kwargs)
OperationalError: unable to open database file
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 136, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 104, in render
    self._set_content(self.rendered_content)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 81, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 48, in top-level template code
    {% if perms.scrum.add_team %}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 376, in getattr
    return obj[attribute]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/context_processors.py", line 12, in __getitem__
    return self.user.has_perm("%s.%s" % (self.module_name, perm_name))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 248, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 16, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 8, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 98, in get_user
    user_id = request.session[SESSION_KEY]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 39, in __getitem__
    return self._session[key]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 165, in _get_session
    self._session_cache = self.load()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/cached_db.py", line 32, in load
    data = super(SessionStore, self).load()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 23, in load
    self.create()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 35, in create
    self.save(must_create=True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/cached_db.py", line 42, in save
    super(SessionStore, self).save(must_create)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 58, in save
    obj.save(force_insert=must_create, using=using)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 551, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 203, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/query.py", line 1593, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 912, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 344, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: attempt to write a readonly database
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 136, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 104, in render
    self._set_content(self.rendered_content)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 81, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 48, in top-level template code
    {% if perms.scrum.add_team %}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 376, in getattr
    return obj[attribute]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/context_processors.py", line 12, in __getitem__
    return self.user.has_perm("%s.%s" % (self.module_name, perm_name))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 248, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 16, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 8, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 98, in get_user
    user_id = request.session[SESSION_KEY]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 39, in __getitem__
    return self._session[key]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 165, in _get_session
    self._session_cache = self.load()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/cached_db.py", line 32, in load
    data = super(SessionStore, self).load()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 23, in load
    self.create()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 35, in create
    self.save(must_create=True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/cached_db.py", line 42, in save
    super(SessionStore, self).save(must_create)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 58, in save
    obj.save(force_insert=must_create, using=using)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 551, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 203, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/query.py", line 1593, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 912, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 344, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: attempt to write a readonly database
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 136, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 104, in render
    self._set_content(self.rendered_content)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 81, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 48, in top-level template code
    {% if perms.scrum.add_team %}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 376, in getattr
    return obj[attribute]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/context_processors.py", line 12, in __getitem__
    return self.user.has_perm("%s.%s" % (self.module_name, perm_name))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 248, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 16, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 8, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 98, in get_user
    user_id = request.session[SESSION_KEY]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 39, in __getitem__
    return self._session[key]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 165, in _get_session
    self._session_cache = self.load()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/cached_db.py", line 32, in load
    data = super(SessionStore, self).load()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 23, in load
    self.create()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 35, in create
    self.save(must_create=True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/cached_db.py", line 42, in save
    super(SessionStore, self).save(must_create)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 58, in save
    obj.save(force_insert=must_create, using=using)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 551, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 203, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/query.py", line 1593, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 912, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 344, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: unable to open database file
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 136, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 104, in render
    self._set_content(self.rendered_content)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 81, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 48, in top-level template code
    {% if perms.scrum.add_team %}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 376, in getattr
    return obj[attribute]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/context_processors.py", line 12, in __getitem__
    return self.user.has_perm("%s.%s" % (self.module_name, perm_name))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 248, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 16, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 8, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 98, in get_user
    user_id = request.session[SESSION_KEY]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 39, in __getitem__
    return self._session[key]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 165, in _get_session
    self._session_cache = self.load()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/cached_db.py", line 32, in load
    data = super(SessionStore, self).load()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 23, in load
    self.create()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 35, in create
    self.save(must_create=True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/cached_db.py", line 42, in save
    super(SessionStore, self).save(must_create)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 58, in save
    obj.save(force_insert=must_create, using=using)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 551, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 203, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/query.py", line 1593, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 912, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 344, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: unable to open database file
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 136, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 104, in render
    self._set_content(self.rendered_content)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 81, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 48, in top-level template code
    {% if perms.scrum.add_team %}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 376, in getattr
    return obj[attribute]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/context_processors.py", line 12, in __getitem__
    return self.user.has_perm("%s.%s" % (self.module_name, perm_name))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 248, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 16, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 8, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 98, in get_user
    user_id = request.session[SESSION_KEY]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 39, in __getitem__
    return self._session[key]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 165, in _get_session
    self._session_cache = self.load()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/cached_db.py", line 32, in load
    data = super(SessionStore, self).load()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 23, in load
    self.create()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 35, in create
    self.save(must_create=True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/cached_db.py", line 42, in save
    super(SessionStore, self).save(must_create)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 58, in save
    obj.save(force_insert=must_create, using=using)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 551, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 203, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/query.py", line 1593, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 912, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 344, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: unable to open database file
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 136, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 104, in render
    self._set_content(self.rendered_content)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 81, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 48, in top-level template code
    {% if perms.scrum.add_team %}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 376, in getattr
    return obj[attribute]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/context_processors.py", line 12, in __getitem__
    return self.user.has_perm("%s.%s" % (self.module_name, perm_name))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 248, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 16, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 8, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 98, in get_user
    user_id = request.session[SESSION_KEY]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 39, in __getitem__
    return self._session[key]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 165, in _get_session
    self._session_cache = self.load()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/cached_db.py", line 32, in load
    data = super(SessionStore, self).load()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 23, in load
    self.create()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 35, in create
    self.save(must_create=True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/cached_db.py", line 42, in save
    super(SessionStore, self).save(must_create)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 58, in save
    obj.save(force_insert=must_create, using=using)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 551, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 203, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/query.py", line 1593, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 912, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 344, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: attempt to write a readonly database
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 136, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 104, in render
    self._set_content(self.rendered_content)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 81, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 48, in top-level template code
    {% if perms.scrum.add_team %}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 376, in getattr
    return obj[attribute]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/context_processors.py", line 12, in __getitem__
    return self.user.has_perm("%s.%s" % (self.module_name, perm_name))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 248, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 16, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 8, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 98, in get_user
    user_id = request.session[SESSION_KEY]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 39, in __getitem__
    return self._session[key]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 165, in _get_session
    self._session_cache = self.load()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/cached_db.py", line 32, in load
    data = super(SessionStore, self).load()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 23, in load
    self.create()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 35, in create
    self.save(must_create=True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/cached_db.py", line 42, in save
    super(SessionStore, self).save(must_create)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 58, in save
    obj.save(force_insert=must_create, using=using)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 551, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 203, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/query.py", line 1593, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 912, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 344, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: unable to open database file
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 136, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 104, in render
    self._set_content(self.rendered_content)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 81, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 48, in top-level template code
    {% if perms.scrum.add_team %}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 376, in getattr
    return obj[attribute]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/context_processors.py", line 12, in __getitem__
    return self.user.has_perm("%s.%s" % (self.module_name, perm_name))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 248, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 16, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 8, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 98, in get_user
    user_id = request.session[SESSION_KEY]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 39, in __getitem__
    return self._session[key]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 165, in _get_session
    self._session_cache = self.load()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/cached_db.py", line 32, in load
    data = super(SessionStore, self).load()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 23, in load
    self.create()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 35, in create
    self.save(must_create=True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/cached_db.py", line 42, in save
    super(SessionStore, self).save(must_create)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 58, in save
    obj.save(force_insert=must_create, using=using)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 551, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 203, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/query.py", line 1593, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 912, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 344, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: unable to open database file
