2014-01-13 12:54:46,202 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 136, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 104, in render
    self._set_content(self.rendered_content)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 81, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 48, in top-level template code
    {% if perms.scrum.add_team %}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 376, in getattr
    return obj[attribute]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/context_processors.py", line 12, in __getitem__
    return self.user.has_perm("%s.%s" % (self.module_name, perm_name))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 248, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 16, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 8, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 98, in get_user
    user_id = request.session[SESSION_KEY]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 39, in __getitem__
    return self._session[key]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 165, in _get_session
    self._session_cache = self.load()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/cached_db.py", line 32, in load
    data = super(SessionStore, self).load()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 19, in load
    expire_date__gt=timezone.now()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 131, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/query.py", line 361, in get
    num = len(clone)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/query.py", line 85, in __len__
    self._result_cache = list(self.iterator())
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/query.py", line 291, in iterator
    for row in compiler.results_iter():
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 763, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 817, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/backends/__init__.py", line 319, in cursor
    cursor = util.CursorWrapper(self._cursor(), self)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 288, in _cursor
    self._sqlite_create_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 278, in _sqlite_create_connection
    self.connection = Database.connect(**kwargs)
OperationalError: unable to open database file
2014-01-13 13:53:07,550 [ERROR] django.request: Internal Server Error: /p/111111/edit/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 51, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 50, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 191, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 132, in get
    return self.render_to_response(self.get_context_data(form=form))
  File "/usr/local/django/scrumbugz/scrum/views.py", line 158, in get_context_data
    for prod, comps in bugzilla.get_products_simplified().items():
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 159, in get_products_simplified
    products = self.get_products()
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 153, in get_products
    products = self.Product.get(prod_query)['products']
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1157, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2014-01-13 13:57:03,747 [ERROR] django.request: Internal Server Error: /p/111111/edit/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 51, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 50, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 191, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 132, in get
    return self.render_to_response(self.get_context_data(form=form))
  File "/usr/local/django/scrumbugz/scrum/views.py", line 158, in get_context_data
    for prod, comps in bugzilla.get_products_simplified().items():
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 159, in get_products_simplified
    products = self.get_products()
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 153, in get_products
    products = self.Product.get(prod_query)['products']
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1157, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2014-01-13 13:57:25,752 [ERROR] django.request: Internal Server Error: /p/new/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 41, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 40, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 168, in get
    return super(BaseCreateView, self).get(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 132, in get
    return self.render_to_response(self.get_context_data(form=form))
  File "/usr/local/django/scrumbugz/scrum/views.py", line 158, in get_context_data
    for prod, comps in bugzilla.get_products_simplified().items():
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 159, in get_products_simplified
    products = self.get_products()
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 153, in get_products
    products = self.Product.get(prod_query)['products']
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1157, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2014-01-13 14:07:01,601 [ERROR] django.request: Internal Server Error: /p/new/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 41, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 40, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 168, in get
    return super(BaseCreateView, self).get(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 132, in get
    return self.render_to_response(self.get_context_data(form=form))
  File "/usr/local/django/scrumbugz/scrum/views.py", line 158, in get_context_data
    for prod, comps in bugzilla.get_products_simplified().items():
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 159, in get_products_simplified
    products = self.get_products()
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 153, in get_products
    products = self.Product.get(prod_query)['products']
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1157, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2014-01-13 14:08:20,034 [ERROR] django.request: Internal Server Error: /p/Wikibase/edit/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 51, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 50, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 191, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 132, in get
    return self.render_to_response(self.get_context_data(form=form))
  File "/usr/local/django/scrumbugz/scrum/views.py", line 158, in get_context_data
    for prod, comps in bugzilla.get_products_simplified().items():
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 159, in get_products_simplified
    products = self.get_products()
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 153, in get_products
    products = self.Product.get(prod_query)['products']
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1157, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2014-01-13 14:27:57,730 [ERROR] django.request: Internal Server Error: /p/Wikibase/edit/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 51, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 50, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 191, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 132, in get
    return self.render_to_response(self.get_context_data(form=form))
  File "/usr/local/django/scrumbugz/scrum/views.py", line 158, in get_context_data
    for prod, comps in bugzilla.get_products_simplified().items():
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 159, in get_products_simplified
    products = self.get_products()
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 153, in get_products
    products = self.Product.get(prod_query)['products']
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1157, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2014-01-13 14:31:09,923 [WARNING] django.request: Not Found: /p/Wikibase/
2014-01-13 14:31:16,626 [ERROR] django.request: Internal Server Error: /p/new/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 41, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 40, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 168, in get
    return super(BaseCreateView, self).get(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 132, in get
    return self.render_to_response(self.get_context_data(form=form))
  File "/usr/local/django/scrumbugz/scrum/views.py", line 158, in get_context_data
    for prod, comps in bugzilla.get_products_simplified().items():
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 159, in get_products_simplified
    products = self.get_products()
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 153, in get_products
    products = self.Product.get(prod_query)['products']
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1157, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2014-01-13 14:33:13,460 [ERROR] django.request: Internal Server Error: /p/new/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 41, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 40, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 168, in get
    return super(BaseCreateView, self).get(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 132, in get
    return self.render_to_response(self.get_context_data(form=form))
  File "/usr/local/django/scrumbugz/scrum/views.py", line 158, in get_context_data
    for prod, comps in bugzilla.get_products_simplified().items():
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 159, in get_products_simplified
    products = self.get_products()
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 153, in get_products
    products = self.Product.get(prod_query)['products']
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1157, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2014-01-13 14:33:44,562 [ERROR] django.request: Internal Server Error: /p/new/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 41, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 40, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 168, in get
    return super(BaseCreateView, self).get(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 132, in get
    return self.render_to_response(self.get_context_data(form=form))
  File "/usr/local/django/scrumbugz/scrum/views.py", line 158, in get_context_data
    for prod, comps in bugzilla.get_products_simplified().items():
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 159, in get_products_simplified
    products = self.get_products()
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 153, in get_products
    products = self.Product.get(prod_query)['products']
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1157, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2014-01-13 14:35:56,271 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/edit/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 51, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 50, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 191, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 132, in get
    return self.render_to_response(self.get_context_data(form=form))
  File "/usr/local/django/scrumbugz/scrum/views.py", line 158, in get_context_data
    for prod, comps in bugzilla.get_products_simplified().items():
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 159, in get_products_simplified
    products = self.get_products()
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 153, in get_products
    products = self.Product.get(prod_query)['products']
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1157, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2014-01-13 14:38:45,852 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/edit/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 51, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 50, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 191, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 132, in get
    return self.render_to_response(self.get_context_data(form=form))
  File "/usr/local/django/scrumbugz/scrum/views.py", line 158, in get_context_data
    for prod, comps in bugzilla.get_products_simplified().items():
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 159, in get_products_simplified
    products = self.get_products()
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 153, in get_products
    products = self.Product.get(prod_query)['products']
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1157, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2014-01-13 14:39:41,723 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/edit/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 51, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 50, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 191, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 132, in get
    return self.render_to_response(self.get_context_data(form=form))
  File "/usr/local/django/scrumbugz/scrum/views.py", line 158, in get_context_data
    for prod, comps in bugzilla.get_products_simplified().items():
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 159, in get_products_simplified
    products = self.get_products()
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 153, in get_products
    products = self.Product.get(prod_query)['products']
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1157, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2014-01-13 14:50:35,146 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/edit/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 51, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 50, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 191, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 132, in get
    return self.render_to_response(self.get_context_data(form=form))
  File "/usr/local/django/scrumbugz/scrum/views.py", line 158, in get_context_data
    for prod, comps in bugzilla.get_products_simplified().items():
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 159, in get_products_simplified
    products = self.get_products()
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 153, in get_products
    products = self.Product.get(prod_query)['products']
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1157, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2014-01-13 14:50:57,398 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/edit/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 51, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 50, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 191, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 132, in get
    return self.render_to_response(self.get_context_data(form=form))
  File "/usr/local/django/scrumbugz/scrum/views.py", line 158, in get_context_data
    for prod, comps in bugzilla.get_products_simplified().items():
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 159, in get_products_simplified
    products = self.get_products()
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 153, in get_products
    products = self.Product.get(prod_query)['products']
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1157, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2014-01-13 14:51:05,567 [ERROR] django.request: Internal Server Error: /p/new/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 41, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 40, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 168, in get
    return super(BaseCreateView, self).get(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 132, in get
    return self.render_to_response(self.get_context_data(form=form))
  File "/usr/local/django/scrumbugz/scrum/views.py", line 158, in get_context_data
    for prod, comps in bugzilla.get_products_simplified().items():
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 159, in get_products_simplified
    products = self.get_products()
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 153, in get_products
    products = self.Product.get(prod_query)['products']
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1157, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2014-01-13 15:18:40,137 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/edit/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 51, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 50, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 191, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 132, in get
    return self.render_to_response(self.get_context_data(form=form))
  File "/usr/local/django/scrumbugz/scrum/views.py", line 158, in get_context_data
    for prod, comps in bugzilla.get_products_simplified().items():
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 159, in get_products_simplified
    products = self.get_products()
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 153, in get_products
    products = self.Product.get(prod_query)['products']
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1157, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2014-01-13 15:19:04,650 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/edit/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 51, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 50, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 191, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 132, in get
    return self.render_to_response(self.get_context_data(form=form))
  File "/usr/local/django/scrumbugz/scrum/views.py", line 158, in get_context_data
    for prod, comps in bugzilla.get_products_simplified().items():
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 159, in get_products_simplified
    products = self.get_products()
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 153, in get_products
    products = self.Product.get(prod_query)['products']
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1157, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2014-01-13 15:28:18,312 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-13 22:03:11,295 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/edit/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 51, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 50, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 191, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 132, in get
    return self.render_to_response(self.get_context_data(form=form))
  File "/usr/local/django/scrumbugz/scrum/views.py", line 158, in get_context_data
    for prod, comps in bugzilla.get_products_simplified().items():
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 159, in get_products_simplified
    products = self.get_products()
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 153, in get_products
    products = self.Product.get(prod_query)['products']
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1157, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2014-01-13 22:03:16,157 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/edit/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 51, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 50, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 191, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 132, in get
    return self.render_to_response(self.get_context_data(form=form))
  File "/usr/local/django/scrumbugz/scrum/views.py", line 158, in get_context_data
    for prod, comps in bugzilla.get_products_simplified().items():
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 159, in get_products_simplified
    products = self.get_products()
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 153, in get_products
    products = self.Product.get(prod_query)['products']
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1157, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2014-01-13 22:19:28,352 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/edit/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 51, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 50, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 191, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 132, in get
    return self.render_to_response(self.get_context_data(form=form))
  File "/usr/local/django/scrumbugz/scrum/views.py", line 158, in get_context_data
    for prod, comps in bugzilla.get_products_simplified().items():
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 159, in get_products_simplified
    products = self.get_products()
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 153, in get_products
    products = self.Product.get(prod_query)['products']
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1157, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2014-01-13 22:19:33,852 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/edit/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 51, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 50, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 191, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 132, in get
    return self.render_to_response(self.get_context_data(form=form))
  File "/usr/local/django/scrumbugz/scrum/views.py", line 158, in get_context_data
    for prod, comps in bugzilla.get_products_simplified().items():
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 159, in get_products_simplified
    products = self.get_products()
  File "/usr/local/django/scrumbugz/bugzilla/api.py", line 153, in get_products
    products = self.Product.get(prod_query)['products']
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1157, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2014-01-13 22:44:10,406 [WARNING] django.request: Not Found: /xmlrpc.cgi
2014-01-13 22:44:10,407 [WARNING] django.request: Forbidden (CSRF cookie not set.): /xmlrpc.cgi
2014-01-13 22:49:35,895 [WARNING] django.request: Not Found: /xmlrpc.cgi
2014-01-13 22:49:35,896 [WARNING] django.request: Forbidden (CSRF token missing or incorrect.): /xmlrpc.cgi
2014-01-13 22:52:51,290 [WARNING] django.request: Not Found: /xmlrpc.cgi
2014-01-13 22:52:51,291 [WARNING] django.request: Forbidden (CSRF cookie not set.): /xmlrpc.cgi
2014-01-13 23:13:50,568 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/products/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 298, in dispatch
    **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 41, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 40, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 172, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 138, in post
    return self.form_valid(form)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 314, in form_valid
    self.object = form.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 364, in save
    fail_message, commit, construct=False)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 86, in save_instance
    instance.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 565, in save_base
    created=(not record_exists), raw=raw, using=using)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/django/scrumbugz/scrum/models.py", line 1007, in fetch_product_bugs
    update_product.delay(*args)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 343, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 469, in apply_async
    **options)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/amqp.py", line 214, in publish_task
    **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/messaging.py", line 164, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 470, in _ensured
    interval_max)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 396, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/utils/__init__.py", line 217, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 246, in connect
    return self.connection
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 761, in connection
    self._connection = self._establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 720, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 115, in establish_connection
    conn = self.Connection(**opts)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/connection.py", line 136, in __init__
    self.transport = create_transport(host, connect_timeout, ssl)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 264, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 99, in __init__
    raise socket.error(last_err)
error: [Errno 111] Connection refused
2014-01-14 00:23:44,940 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/products/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 298, in dispatch
    **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 41, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 40, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 172, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 138, in post
    return self.form_valid(form)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 314, in form_valid
    self.object = form.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 364, in save
    fail_message, commit, construct=False)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 86, in save_instance
    instance.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 565, in save_base
    created=(not record_exists), raw=raw, using=using)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/django/scrumbugz/scrum/models.py", line 1007, in fetch_product_bugs
    update_product.delay(*args)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 343, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 469, in apply_async
    **options)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/amqp.py", line 214, in publish_task
    **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/messaging.py", line 164, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 470, in _ensured
    interval_max)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 396, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/utils/__init__.py", line 217, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 246, in connect
    return self.connection
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 761, in connection
    self._connection = self._establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 720, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 115, in establish_connection
    conn = self.Connection(**opts)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/connection.py", line 136, in __init__
    self.transport = create_transport(host, connect_timeout, ssl)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 264, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 99, in __init__
    raise socket.error(last_err)
error: [Errno 111] Connection refused
2014-01-14 00:26:15,716 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/products/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 298, in dispatch
    **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 41, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 40, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 172, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 138, in post
    return self.form_valid(form)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 314, in form_valid
    self.object = form.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 364, in save
    fail_message, commit, construct=False)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 86, in save_instance
    instance.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 565, in save_base
    created=(not record_exists), raw=raw, using=using)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/django/scrumbugz/scrum/models.py", line 1007, in fetch_product_bugs
    update_product.delay(*args)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 343, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 469, in apply_async
    **options)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/amqp.py", line 214, in publish_task
    **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/messaging.py", line 164, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 470, in _ensured
    interval_max)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 396, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/utils/__init__.py", line 217, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 246, in connect
    return self.connection
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 761, in connection
    self._connection = self._establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 720, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 115, in establish_connection
    conn = self.Connection(**opts)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/connection.py", line 136, in __init__
    self.transport = create_transport(host, connect_timeout, ssl)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 264, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 99, in __init__
    raise socket.error(last_err)
error: [Errno 111] Connection refused
2014-01-14 01:11:41,661 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/products/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 298, in dispatch
    **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 41, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 40, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 172, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 138, in post
    return self.form_valid(form)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 314, in form_valid
    self.object = form.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 364, in save
    fail_message, commit, construct=False)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 86, in save_instance
    instance.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 565, in save_base
    created=(not record_exists), raw=raw, using=using)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/django/scrumbugz/scrum/models.py", line 1007, in fetch_product_bugs
    update_product.delay(*args)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 343, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 469, in apply_async
    **options)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/amqp.py", line 214, in publish_task
    **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/messaging.py", line 164, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 470, in _ensured
    interval_max)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 396, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/utils/__init__.py", line 217, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 246, in connect
    return self.connection
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 761, in connection
    self._connection = self._establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 720, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 115, in establish_connection
    conn = self.Connection(**opts)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/connection.py", line 136, in __init__
    self.transport = create_transport(host, connect_timeout, ssl)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 264, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 99, in __init__
    raise socket.error(last_err)
error: [Errno 111] Connection refused
2014-01-14 10:14:24,005 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/products/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 298, in dispatch
    **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 41, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 40, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 172, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 138, in post
    return self.form_valid(form)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 314, in form_valid
    self.object = form.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 364, in save
    fail_message, commit, construct=False)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 86, in save_instance
    instance.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 565, in save_base
    created=(not record_exists), raw=raw, using=using)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/django/scrumbugz/scrum/models.py", line 1007, in fetch_product_bugs
    update_product.delay(*args)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 343, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 469, in apply_async
    **options)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/amqp.py", line 214, in publish_task
    **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/messaging.py", line 164, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 470, in _ensured
    interval_max)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 396, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/utils/__init__.py", line 217, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 246, in connect
    return self.connection
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 761, in connection
    self._connection = self._establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 720, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 115, in establish_connection
    conn = self.Connection(**opts)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/connection.py", line 136, in __init__
    self.transport = create_transport(host, connect_timeout, ssl)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 264, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 99, in __init__
    raise socket.error(last_err)
error: [Errno 111] Connection refused
2014-01-14 10:42:23,333 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/products/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 298, in dispatch
    **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 41, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 40, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 172, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 138, in post
    return self.form_valid(form)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 314, in form_valid
    self.object = form.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 364, in save
    fail_message, commit, construct=False)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 86, in save_instance
    instance.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 565, in save_base
    created=(not record_exists), raw=raw, using=using)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/django/scrumbugz/scrum/models.py", line 1007, in fetch_product_bugs
    update_product.delay(*args)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 343, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 469, in apply_async
    **options)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/amqp.py", line 214, in publish_task
    **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/messaging.py", line 164, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 470, in _ensured
    interval_max)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 396, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/utils/__init__.py", line 217, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 246, in connect
    return self.connection
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 761, in connection
    self._connection = self._establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 720, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 115, in establish_connection
    conn = self.Connection(**opts)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/connection.py", line 136, in __init__
    self.transport = create_transport(host, connect_timeout, ssl)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 264, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 99, in __init__
    raise socket.error(last_err)
error: [Errno 111] Connection refused
2014-01-14 10:45:52,315 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/products/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 298, in dispatch
    **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 41, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 40, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 172, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 138, in post
    return self.form_valid(form)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 314, in form_valid
    self.object = form.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 364, in save
    fail_message, commit, construct=False)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 86, in save_instance
    instance.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 565, in save_base
    created=(not record_exists), raw=raw, using=using)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/django/scrumbugz/scrum/models.py", line 1007, in fetch_product_bugs
    update_product.delay(*args)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 343, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 469, in apply_async
    **options)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/amqp.py", line 214, in publish_task
    **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/messaging.py", line 164, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 470, in _ensured
    interval_max)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 396, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/utils/__init__.py", line 217, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 246, in connect
    return self.connection
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 761, in connection
    self._connection = self._establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 720, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 115, in establish_connection
    conn = self.Connection(**opts)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/connection.py", line 136, in __init__
    self.transport = create_transport(host, connect_timeout, ssl)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 264, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 99, in __init__
    raise socket.error(last_err)
error: [Errno 111] Connection refused
2014-01-14 10:56:01,577 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/products/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 298, in dispatch
    **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 41, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 40, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 172, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 138, in post
    return self.form_valid(form)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 314, in form_valid
    self.object = form.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 364, in save
    fail_message, commit, construct=False)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 86, in save_instance
    instance.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 565, in save_base
    created=(not record_exists), raw=raw, using=using)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/django/scrumbugz/scrum/models.py", line 1007, in fetch_product_bugs
    update_product.delay(*args)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 343, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 469, in apply_async
    **options)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/amqp.py", line 214, in publish_task
    **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/messaging.py", line 164, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 470, in _ensured
    interval_max)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 396, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/utils/__init__.py", line 217, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 246, in connect
    return self.connection
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 761, in connection
    self._connection = self._establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 720, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 115, in establish_connection
    conn = self.Connection(**opts)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/connection.py", line 136, in __init__
    self.transport = create_transport(host, connect_timeout, ssl)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 264, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 99, in __init__
    raise socket.error(last_err)
error: [Errno 111] Connection refused
2014-01-14 11:09:31,651 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/products/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 298, in dispatch
    **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 41, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 40, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 172, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 138, in post
    return self.form_valid(form)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 314, in form_valid
    self.object = form.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 364, in save
    fail_message, commit, construct=False)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 86, in save_instance
    instance.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 565, in save_base
    created=(not record_exists), raw=raw, using=using)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/django/scrumbugz/scrum/models.py", line 1007, in fetch_product_bugs
    update_product.delay(*args)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 343, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 469, in apply_async
    **options)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/amqp.py", line 214, in publish_task
    **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/messaging.py", line 164, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 470, in _ensured
    interval_max)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 396, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/utils/__init__.py", line 217, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 246, in connect
    return self.connection
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 761, in connection
    self._connection = self._establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 720, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 115, in establish_connection
    conn = self.Connection(**opts)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/connection.py", line 136, in __init__
    self.transport = create_transport(host, connect_timeout, ssl)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 264, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 99, in __init__
    raise socket.error(last_err)
error: [Errno 111] Connection refused
2014-01-14 11:37:12,252 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/products/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 298, in dispatch
    **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 41, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 40, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 172, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 138, in post
    return self.form_valid(form)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 314, in form_valid
    self.object = form.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 364, in save
    fail_message, commit, construct=False)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 86, in save_instance
    instance.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 565, in save_base
    created=(not record_exists), raw=raw, using=using)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/django/scrumbugz/scrum/models.py", line 1007, in fetch_product_bugs
    update_product.delay(*args)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 343, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 469, in apply_async
    **options)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/amqp.py", line 214, in publish_task
    **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/messaging.py", line 164, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 470, in _ensured
    interval_max)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 396, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/utils/__init__.py", line 217, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 246, in connect
    return self.connection
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 761, in connection
    self._connection = self._establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 720, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 115, in establish_connection
    conn = self.Connection(**opts)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/connection.py", line 136, in __init__
    self.transport = create_transport(host, connect_timeout, ssl)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 264, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 99, in __init__
    raise socket.error(last_err)
error: [Errno 111] Connection refused
2014-01-14 11:42:27,363 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/products/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 298, in dispatch
    **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 41, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 40, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 172, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 138, in post
    return self.form_valid(form)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 314, in form_valid
    self.object = form.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 364, in save
    fail_message, commit, construct=False)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 86, in save_instance
    instance.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 565, in save_base
    created=(not record_exists), raw=raw, using=using)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/django/scrumbugz/scrum/models.py", line 1007, in fetch_product_bugs
    update_product.delay(*args)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 343, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 469, in apply_async
    **options)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/amqp.py", line 214, in publish_task
    **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/messaging.py", line 164, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 470, in _ensured
    interval_max)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 396, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/utils/__init__.py", line 217, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 246, in connect
    return self.connection
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 761, in connection
    self._connection = self._establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 720, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 115, in establish_connection
    conn = self.Connection(**opts)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/connection.py", line 136, in __init__
    self.transport = create_transport(host, connect_timeout, ssl)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 264, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 99, in __init__
    raise socket.error(last_err)
error: [Errno 111] Connection refused
2014-01-14 11:51:13,084 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/products/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 298, in dispatch
    **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 41, in dispatch
    return wrap(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 40, in wrap
    *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 172, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 138, in post
    return self.form_valid(form)
  File "/usr/local/django/scrumbugz/scrum/views.py", line 314, in form_valid
    self.object = form.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 364, in save
    fail_message, commit, construct=False)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/models.py", line 86, in save_instance
    instance.save()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 565, in save_base
    created=(not record_exists), raw=raw, using=using)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/django/scrumbugz/scrum/models.py", line 1007, in fetch_product_bugs
    update_product.delay(*args)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 343, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/task.py", line 469, in apply_async
    **options)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/celery/app/amqp.py", line 214, in publish_task
    **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/messaging.py", line 164, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 470, in _ensured
    interval_max)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 396, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/utils/__init__.py", line 217, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 246, in connect
    return self.connection
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 761, in connection
    self._connection = self._establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/connection.py", line 720, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 115, in establish_connection
    conn = self.Connection(**opts)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/connection.py", line 136, in __init__
    self.transport = create_transport(host, connect_timeout, ssl)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 264, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/amqp/transport.py", line 99, in __init__
    raise socket.error(last_err)
error: [Errno 111] Connection refused
2014-01-14 12:17:20,495 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/backlog/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 136, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 104, in render
    self._set_content(self.rendered_content)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 81, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/project_backlog.html", line 2, in top-level template code
    {% from "scrum/includes/macros.html" import toggle_stats_button, bug_table with context %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/base_project.html", line 2, in top-level template code
    {% from "scrum/includes/macros.html" import left_nav %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/base.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 102, in top-level template code
    {% block content %}{% endblock %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/project_backlog.html", line 58, in block "content"
    {{ bug_table(bugs, 'backlog_table', blocked_bugs=blocked_bugs, flagged_bugs=flagged_bugs, show_project=False) }}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/includes/macros.html", line 60, in template
    <a href="{{ bug.get_bugzilla_url() }}" title="Open in Bugzilla"><img src="{{ STATIC_URL }}img/bugzilla.png" alt="Open in Bugzilla"> {{ bug.id }}</a>
  File "/usr/local/django/scrumbugz/scrum/models.py", line 668, in get_bugzilla_url
    return '%sid=%s' % (settings.BUGZILLA_SHOW_URL, self.id)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 185, in inner
    return func(self._wrapped, *args)
AttributeError: 'Settings' object has no attribute 'BUGZILLA_SHOW_URL'
2014-01-14 12:17:32,205 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/backlog/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 136, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 104, in render
    self._set_content(self.rendered_content)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 81, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/project_backlog.html", line 2, in top-level template code
    {% from "scrum/includes/macros.html" import toggle_stats_button, bug_table with context %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/base_project.html", line 2, in top-level template code
    {% from "scrum/includes/macros.html" import left_nav %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/base.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 102, in top-level template code
    {% block content %}{% endblock %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/project_backlog.html", line 58, in block "content"
    {{ bug_table(bugs, 'backlog_table', blocked_bugs=blocked_bugs, flagged_bugs=flagged_bugs, show_project=False) }}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/includes/macros.html", line 60, in template
    <a href="{{ bug.get_bugzilla_url() }}" title="Open in Bugzilla"><img src="{{ STATIC_URL }}img/bugzilla.png" alt="Open in Bugzilla"> {{ bug.id }}</a>
  File "/usr/local/django/scrumbugz/scrum/models.py", line 668, in get_bugzilla_url
    return '%sid=%s' % (settings.BUGZILLA_SHOW_URL, self.id)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 185, in inner
    return func(self._wrapped, *args)
AttributeError: 'Settings' object has no attribute 'BUGZILLA_SHOW_URL'
2014-01-14 12:21:29,317 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/backlog/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 136, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 104, in render
    self._set_content(self.rendered_content)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 81, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/project_backlog.html", line 2, in top-level template code
    {% from "scrum/includes/macros.html" import toggle_stats_button, bug_table with context %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/base_project.html", line 2, in top-level template code
    {% from "scrum/includes/macros.html" import left_nav %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/base.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 102, in top-level template code
    {% block content %}{% endblock %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/project_backlog.html", line 58, in block "content"
    {{ bug_table(bugs, 'backlog_table', blocked_bugs=blocked_bugs, flagged_bugs=flagged_bugs, show_project=False) }}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/includes/macros.html", line 60, in template
    <a href="{{ bug.get_bugzilla_url() }}" title="Open in Bugzilla"><img src="{{ STATIC_URL }}img/bugzilla.png" alt="Open in Bugzilla"> {{ bug.id }}</a>
  File "/usr/local/django/scrumbugz/scrum/models.py", line 668, in get_bugzilla_url
    return '%sid=%s' % (settings.BUGZILLA_SHOW_URL, self.id)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 185, in inner
    return func(self._wrapped, *args)
AttributeError: 'Settings' object has no attribute 'BUGZILLA_SHOW_URL'
2014-01-14 12:21:33,883 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/backlog/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 136, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 104, in render
    self._set_content(self.rendered_content)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 81, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/project_backlog.html", line 2, in top-level template code
    {% from "scrum/includes/macros.html" import toggle_stats_button, bug_table with context %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/base_project.html", line 2, in top-level template code
    {% from "scrum/includes/macros.html" import left_nav %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/base.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 102, in top-level template code
    {% block content %}{% endblock %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/project_backlog.html", line 58, in block "content"
    {{ bug_table(bugs, 'backlog_table', blocked_bugs=blocked_bugs, flagged_bugs=flagged_bugs, show_project=False) }}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/includes/macros.html", line 60, in template
    <a href="{{ bug.get_bugzilla_url() }}" title="Open in Bugzilla"><img src="{{ STATIC_URL }}img/bugzilla.png" alt="Open in Bugzilla"> {{ bug.id }}</a>
  File "/usr/local/django/scrumbugz/scrum/models.py", line 668, in get_bugzilla_url
    return '%sid=%s' % (settings.BUGZILLA_SHOW_URL, self.id)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 185, in inner
    return func(self._wrapped, *args)
AttributeError: 'Settings' object has no attribute 'BUGZILLA_SHOW_URL'
